services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=studentenrollmentsystemef;Username=postgres;Password=ccms
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ccms
      POSTGRES_DB: studentenrollmentsystemef
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres -d studentenrollmentsystemef"]
        interval: 5s
        timeout: 5s
        retries: 5
volumes:
  postgres_data: