@EnrollmentSystemAPI_HostAddress = http://localhost:5149

GET {{EnrollmentSystemAPI_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{EnrollmentSystemAPI_HostAddress}}/api/section/1/student/3
Accept: application/json

Content-Length: 